services:
    janus:
        build: ./janus
        ports:
            - 1200:1200
        # entrypoint: "sleep infinity"
    video:
        build: ./video
        volumes:
            - data:/data
        # entrypoint: "sleep infinity"
    web:
        build: ./web
        ports:
            - 1100:1100
        volumes:
            - data:/data
        # entrypoint: "sleep infinity"
volumes:
    data: